/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazg;

/**
 *
 * @author JOHAN
 */
public class Cola extends javax.swing.JFrame {

    /**
     * Creates new form Cola
     */
    public Cola() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mx = new javax.swing.JLabel();
        encolar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Densencolar = new javax.swing.JButton();
        INICIO = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        mx.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mx.setForeground(new java.awt.Color(255, 255, 255));
        mx.setText("COLA DINÁMICA - FIFO");
        getContentPane().add(mx, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        encolar.setBackground(new java.awt.Color(255, 0, 102));
        encolar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        encolar.setForeground(new java.awt.Color(255, 255, 255));
        encolar.setText("ENCOLAR");
        getContentPane().add(encolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 210, 50));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 550, 130));

        Densencolar.setBackground(new java.awt.Color(255, 0, 102));
        Densencolar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Densencolar.setForeground(new java.awt.Color(255, 255, 255));
        Densencolar.setText("DESENCOLAR");
        getContentPane().add(Densencolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, 50));

        INICIO.setBackground(new java.awt.Color(255, 0, 102));
        INICIO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        INICIO.setForeground(new java.awt.Color(255, 255, 255));
        INICIO.setText("INICIO");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        getContentPane().add(INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cola.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 544));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        pincipal p=new pincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_INICIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Densencolar;
    private javax.swing.JButton INICIO;
    private javax.swing.JButton encolar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mx;
    // End of variables declaration//GEN-END:variables
}
