/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazg;

/**
 *
 * @author JOHAN
 */
import PilaD.Nodo;
import PilaD.PilaD;
import javax.swing.*;
import javax.swing.JOptionPane;
public class Pila extends javax.swing.JFrame {

    /**
     * Creates new form Pila
     */
    public Pila() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        apilar = new javax.swing.JButton();
        vista = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        desapilar = new javax.swing.JButton();
        INICIO = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        texto.setBackground(new java.awt.Color(255, 255, 255));
        texto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setText("PILA -LIFO");
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 40));

        apilar.setBackground(new java.awt.Color(255, 0, 0));
        apilar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        apilar.setForeground(new java.awt.Color(255, 255, 255));
        apilar.setText("APILAR");
        apilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apilarActionPerformed(evt);
            }
        });
        getContentPane().add(apilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 140, 60));

        vista.setViewportView(panel);

        getContentPane().add(vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 510, 140));

        desapilar.setBackground(new java.awt.Color(255, 0, 0));
        desapilar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        desapilar.setForeground(new java.awt.Color(255, 255, 255));
        desapilar.setText("DESAPILAR");
        desapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desapilarActionPerformed(evt);
            }
        });
        getContentPane().add(desapilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 60));

        INICIO.setBackground(new java.awt.Color(255, 0, 0));
        INICIO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        INICIO.setForeground(new java.awt.Color(255, 255, 255));
        INICIO.setText("INICIO");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        getContentPane().add(INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, 60));

        fondo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo22.jpg"))); // NOI18N
        fondo.setText("sssss");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 517));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void apilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apilarActionPerformed
       String dato= JOptionPane.showInputDialog(null,"Digite el dato en la pila ");
    
        
       JLabel label=new JLabel();
       label.setText(p.apilar(dato).getInfo());
       label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
       label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nodod.png")));
        panel.add(label);
        panel.updateUI();
        
    }//GEN-LAST:event_apilarActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        pincipal p =new pincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_INICIOActionPerformed

    private void desapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desapilarActionPerformed
        panel.removeAll();
        if (!p.vacia()){
           p.desapilar();
          Nodo aux=p.getInicio();
            while(aux!=null){
          JLabel label=new JLabel(aux.getInfo());
         aux=aux.getSiguiente();
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
       label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nodod.png")));
       panel.add(label);
       panel.updateUI();}
          
        } else{
            JOptionPane.showMessageDialog(null,"pila vacia no se puede desapilar");
        }
      
       
       
    }//GEN-LAST:event_desapilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INICIO;
    private javax.swing.JButton apilar;
    private javax.swing.JLabel datos;
    private javax.swing.JButton desapilar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel texto;
    private javax.swing.JScrollPane vista;
    // End of variables declaration//GEN-END:variables
PilaD p=new PilaD();

}
