/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazg;

/**
 *
 * @author JOHAN
 */
public class pincipal extends javax.swing.JFrame {

    /**
     * Creates new form pincipal
     */
    public pincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PILA1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PILA = new javax.swing.JButton();
        Cola = new javax.swing.JButton();
        listac = new javax.swing.JButton();
        Listadb = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        PILA1.setBackground(new java.awt.Color(255, 0, 51));
        PILA1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PILA1.setForeground(new java.awt.Color(255, 255, 255));
        PILA1.setText("PILA DINÁMICA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        icono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user4.png"))); // NOI18N
        icono.setToolTipText(getTitle());
        icono.setAlignmentX(-0.5F);
        icono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icono.setName("mmmm"); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));
        icono.getAccessibleContext().setAccessibleParent(getMenuBar());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESCOGE UNA ESTRUCTURA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 260, 30));

        PILA.setBackground(new java.awt.Color(255, 0, 51));
        PILA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PILA.setForeground(new java.awt.Color(255, 255, 255));
        PILA.setText("PILA DINÁMICA");
        PILA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILAActionPerformed(evt);
            }
        });
        getContentPane().add(PILA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 260, 40));

        Cola.setBackground(new java.awt.Color(255, 0, 51));
        Cola.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cola.setForeground(new java.awt.Color(255, 255, 255));
        Cola.setText("COLA DINÁMICA");
        Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaActionPerformed(evt);
            }
        });
        getContentPane().add(Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 260, 40));

        listac.setBackground(new java.awt.Color(255, 0, 51));
        listac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        listac.setForeground(new java.awt.Color(255, 255, 255));
        listac.setText("LISTA CIRCULAR");
        listac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listacActionPerformed(evt);
            }
        });
        getContentPane().add(listac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 260, 40));

        Listadb.setBackground(new java.awt.Color(255, 0, 51));
        Listadb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Listadb.setForeground(new java.awt.Color(255, 255, 255));
        Listadb.setText("LISTA DOBLEMENTE ENLAZADA");
        Listadb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadbActionPerformed(evt);
            }
        });
        getContentPane().add(Listadb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 260, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue-wallpaper-27.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listacActionPerformed

    private void ListadbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListadbActionPerformed

    private void PILAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILAActionPerformed
        Pila p=new Pila();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PILAActionPerformed

    private void ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaActionPerformed
      Cola c = new Cola();
      c.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cola;
    private javax.swing.JButton Listadb;
    private javax.swing.JButton PILA;
    private javax.swing.JButton PILA1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listac;
    // End of variables declaration//GEN-END:variables
}
